// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  name: __t.string(),
  address: __t.string(),
  city: __t.string(),
  pincode: __t.string(),
  logo: __t.string(),
  currency: __t.string(),
  bossName: __t.string().name("boss_name"),
  updatedAt: __t.timestamp().name("updated_at"),
});
