// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  companyAddress: __t.bool().name("company_address"),
  companyCity: __t.bool().name("company_city"),
  companyPincode: __t.bool().name("company_pincode"),
  companyLogo: __t.bool().name("company_logo"),
  employeeId: __t.bool().name("employee_id"),
  designation: __t.bool(),
  paidDays: __t.bool().name("paid_days"),
  lopDays: __t.bool().name("lop_days"),
  paymentDate: __t.bool().name("payment_date"),
  payPeriod: __t.bool().name("pay_period"),
  customFields: __t.bool().name("custom_fields"),
});
