// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddDeductionsTemplateReducer from "./add_deductions_template_reducer";
import AddEarningsTemplateReducer from "./add_earnings_template_reducer";
import ChangePasswordReducer from "./change_password_reducer";
import CreateEmployeeAccountReducer from "./create_employee_account_reducer";
import DeleteDeductionsTemplateReducer from "./delete_deductions_template_reducer";
import DeleteDraftReducer from "./delete_draft_reducer";
import DeleteEarningsTemplateReducer from "./delete_earnings_template_reducer";
import DeleteEmployeeReducer from "./delete_employee_reducer";
import HidePayslipReducer from "./hide_payslip_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import RejectPayslipReducer from "./reject_payslip_reducer";
import RestorePayslipReducer from "./restore_payslip_reducer";
import ResubmitPayslipReducer from "./resubmit_payslip_reducer";
import SignPayslipReducer from "./sign_payslip_reducer";
import SubmitPayslipReducer from "./submit_payslip_reducer";
import UpdateCompanyReducer from "./update_company_reducer";
import UpdateDeductionsTemplateReducer from "./update_deductions_template_reducer";
import UpdateDraftReducer from "./update_draft_reducer";
import UpdateEarningsTemplateReducer from "./update_earnings_template_reducer";
import UpdateEmployeeReducer from "./update_employee_reducer";
import UpdateFieldVisibilityReducer from "./update_field_visibility_reducer";
import UpdateMyProfileReducer from "./update_my_profile_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import CompanyViewRow from "./company_view_table";
import DeductionsTemplatesViewRow from "./deductions_templates_view_table";
import EarningsTemplatesViewRow from "./earnings_templates_view_table";
import EmployeesViewRow from "./employees_view_table";
import FieldVisibilityViewRow from "./field_visibility_view_table";
import HiddenPayslipsViewRow from "./hidden_payslips_view_table";
import SignedPayslipsViewRow from "./signed_payslips_view_table";
import SubmissionsViewRow from "./submissions_view_table";
import UsersViewRow from "./users_view_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  companyView: __table({
    name: 'company_view',
    indexes: [
    ],
    constraints: [
    ],
  }, CompanyViewRow),
  deductionsTemplatesView: __table({
    name: 'deductions_templates_view',
    indexes: [
    ],
    constraints: [
    ],
  }, DeductionsTemplatesViewRow),
  earningsTemplatesView: __table({
    name: 'earnings_templates_view',
    indexes: [
    ],
    constraints: [
    ],
  }, EarningsTemplatesViewRow),
  employeesView: __table({
    name: 'employees_view',
    indexes: [
    ],
    constraints: [
    ],
  }, EmployeesViewRow),
  fieldVisibilityView: __table({
    name: 'field_visibility_view',
    indexes: [
    ],
    constraints: [
    ],
  }, FieldVisibilityViewRow),
  hiddenPayslipsView: __table({
    name: 'hidden_payslips_view',
    indexes: [
    ],
    constraints: [
    ],
  }, HiddenPayslipsViewRow),
  signedPayslipsView: __table({
    name: 'signed_payslips_view',
    indexes: [
    ],
    constraints: [
    ],
  }, SignedPayslipsViewRow),
  submissionsView: __table({
    name: 'submissions_view',
    indexes: [
    ],
    constraints: [
    ],
  }, SubmissionsViewRow),
  usersView: __table({
    name: 'users_view',
    indexes: [
    ],
    constraints: [
    ],
  }, UsersViewRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_deductions_template", AddDeductionsTemplateReducer),
  __reducerSchema("add_earnings_template", AddEarningsTemplateReducer),
  __reducerSchema("change_password", ChangePasswordReducer),
  __reducerSchema("create_employee_account", CreateEmployeeAccountReducer),
  __reducerSchema("delete_deductions_template", DeleteDeductionsTemplateReducer),
  __reducerSchema("delete_draft", DeleteDraftReducer),
  __reducerSchema("delete_earnings_template", DeleteEarningsTemplateReducer),
  __reducerSchema("delete_employee", DeleteEmployeeReducer),
  __reducerSchema("hide_payslip", HidePayslipReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("reject_payslip", RejectPayslipReducer),
  __reducerSchema("restore_payslip", RestorePayslipReducer),
  __reducerSchema("resubmit_payslip", ResubmitPayslipReducer),
  __reducerSchema("sign_payslip", SignPayslipReducer),
  __reducerSchema("submit_payslip", SubmitPayslipReducer),
  __reducerSchema("update_company", UpdateCompanyReducer),
  __reducerSchema("update_deductions_template", UpdateDeductionsTemplateReducer),
  __reducerSchema("update_draft", UpdateDraftReducer),
  __reducerSchema("update_earnings_template", UpdateEarningsTemplateReducer),
  __reducerSchema("update_employee", UpdateEmployeeReducer),
  __reducerSchema("update_field_visibility", UpdateFieldVisibilityReducer),
  __reducerSchema("update_my_profile", UpdateMyProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.3.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

