// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  submissionId: __t.u64().name("submission_id"),
  employeeId: __t.u64().name("employee_id"),
  pdfBase64: __t.string().name("pdf_base_64"),
  signedAt: __t.timestamp().name("signed_at"),
});
