// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  employeeId: __t.u64().name("employee_id"),
  payMonth: __t.u8().name("pay_month"),
  payYear: __t.u16().name("pay_year"),
  paidDays: __t.u8().name("paid_days"),
  lopDays: __t.u8().name("lop_days"),
  paymentDate: __t.string().name("payment_date"),
  earningsJson: __t.string().name("earnings_json"),
  deductionsJson: __t.string().name("deductions_json"),
  customFieldsJson: __t.string().name("custom_fields_json"),
  grossEarnings: __t.u64().name("gross_earnings"),
  totalDeductions: __t.u64().name("total_deductions"),
  netPayable: __t.u64().name("net_payable"),
  amountInWords: __t.string().name("amount_in_words"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
