// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  payMonth: __t.u8(),
  payYear: __t.u16(),
  paidDays: __t.u8(),
  lopDays: __t.u8(),
  paymentDate: __t.string(),
  earningsJson: __t.string(),
  deductionsJson: __t.string(),
  customFieldsJson: __t.string(),
  grossEarnings: __t.u64(),
  totalDeductions: __t.u64(),
  netPayable: __t.u64(),
  amountInWords: __t.string(),
};
