// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Company = __t.object("Company", {
  id: __t.u64(),
  name: __t.string(),
  address: __t.string(),
  city: __t.string(),
  pincode: __t.string(),
  logo: __t.string(),
  currency: __t.string(),
  bossName: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Company = __Infer<typeof Company>;

export const CompanyView = __t.object("CompanyView", {});
export type CompanyView = __Infer<typeof CompanyView>;

export const Credential = __t.object("Credential", {
  userId: __t.u64(),
  passwordHash: __t.string(),
  salt: __t.string(),
});
export type Credential = __Infer<typeof Credential>;

export const DeductionsTemplate = __t.object("DeductionsTemplate", {
  id: __t.u64(),
  name: __t.string(),
  defaultAmount: __t.u64(),
  sortOrder: __t.u16(),
  p: __t.u8(),
});
export type DeductionsTemplate = __Infer<typeof DeductionsTemplate>;

export const DeductionsTemplatesView = __t.object("DeductionsTemplatesView", {});
export type DeductionsTemplatesView = __Infer<typeof DeductionsTemplatesView>;

export const EarningsTemplate = __t.object("EarningsTemplate", {
  id: __t.u64(),
  name: __t.string(),
  defaultAmount: __t.u64(),
  sortOrder: __t.u16(),
  p: __t.u8(),
});
export type EarningsTemplate = __Infer<typeof EarningsTemplate>;

export const EarningsTemplatesView = __t.object("EarningsTemplatesView", {});
export type EarningsTemplatesView = __Infer<typeof EarningsTemplatesView>;

export const Employee = __t.object("Employee", {
  id: __t.u64(),
  userId: __t.u64(),
  name: __t.string(),
  employeeCode: __t.string(),
  designation: __t.string(),
  customFieldsJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Employee = __Infer<typeof Employee>;

export const EmployeesView = __t.object("EmployeesView", {});
export type EmployeesView = __Infer<typeof EmployeesView>;

export const FieldVisibility = __t.object("FieldVisibility", {
  id: __t.u64(),
  companyAddress: __t.bool(),
  companyCity: __t.bool(),
  companyPincode: __t.bool(),
  companyLogo: __t.bool(),
  employeeId: __t.bool(),
  designation: __t.bool(),
  paidDays: __t.bool(),
  lopDays: __t.bool(),
  paymentDate: __t.bool(),
  payPeriod: __t.bool(),
  customFields: __t.bool(),
});
export type FieldVisibility = __Infer<typeof FieldVisibility>;

export const FieldVisibilityView = __t.object("FieldVisibilityView", {});
export type FieldVisibilityView = __Infer<typeof FieldVisibilityView>;

export const HiddenPayslip = __t.object("HiddenPayslip", {
  submissionId: __t.u64(),
  employeeId: __t.u64(),
  reason: __t.string(),
  hiddenByUserId: __t.u64(),
  hiddenAt: __t.timestamp(),
});
export type HiddenPayslip = __Infer<typeof HiddenPayslip>;

export const HiddenPayslipsView = __t.object("HiddenPayslipsView", {});
export type HiddenPayslipsView = __Infer<typeof HiddenPayslipsView>;

export const PayslipSubmission = __t.object("PayslipSubmission", {
  id: __t.u64(),
  employeeId: __t.u64(),
  payMonth: __t.u8(),
  payYear: __t.u16(),
  paidDays: __t.u8(),
  lopDays: __t.u8(),
  paymentDate: __t.string(),
  earningsJson: __t.string(),
  deductionsJson: __t.string(),
  customFieldsJson: __t.string(),
  grossEarnings: __t.u64(),
  totalDeductions: __t.u64(),
  netPayable: __t.u64(),
  amountInWords: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PayslipSubmission = __Infer<typeof PayslipSubmission>;

export const PayslipVisibilityEvent = __t.object("PayslipVisibilityEvent", {
  id: __t.u64(),
  submissionId: __t.u64(),
  actorUserId: __t.u64(),
  action: __t.string(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type PayslipVisibilityEvent = __Infer<typeof PayslipVisibilityEvent>;

export const SignedPayslip = __t.object("SignedPayslip", {
  submissionId: __t.u64(),
  employeeId: __t.u64(),
  pdfBase64: __t.string(),
  signedAt: __t.timestamp(),
});
export type SignedPayslip = __Infer<typeof SignedPayslip>;

export const SignedPayslipsView = __t.object("SignedPayslipsView", {});
export type SignedPayslipsView = __Infer<typeof SignedPayslipsView>;

export const SubmissionsView = __t.object("SubmissionsView", {});
export type SubmissionsView = __Infer<typeof SubmissionsView>;

export const User = __t.object("User", {
  id: __t.u64(),
  username: __t.string(),
  name: __t.string(),
  role: __t.string(),
  identity: __t.option(__t.identity()),
  employeeId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UsersView = __t.object("UsersView", {});
export type UsersView = __Infer<typeof UsersView>;

