// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  companyAddress: __t.bool(),
  companyCity: __t.bool(),
  companyPincode: __t.bool(),
  companyLogo: __t.bool(),
  employeeId: __t.bool(),
  designation: __t.bool(),
  paidDays: __t.bool(),
  lopDays: __t.bool(),
  paymentDate: __t.bool(),
  payPeriod: __t.bool(),
  customFields: __t.bool(),
};
