// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddDeductionsTemplateReducer from "../add_deductions_template_reducer";
import AddEarningsTemplateReducer from "../add_earnings_template_reducer";
import ChangePasswordReducer from "../change_password_reducer";
import CreateEmployeeAccountReducer from "../create_employee_account_reducer";
import DeleteDeductionsTemplateReducer from "../delete_deductions_template_reducer";
import DeleteDraftReducer from "../delete_draft_reducer";
import DeleteEarningsTemplateReducer from "../delete_earnings_template_reducer";
import DeleteEmployeeReducer from "../delete_employee_reducer";
import HidePayslipReducer from "../hide_payslip_reducer";
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import RejectPayslipReducer from "../reject_payslip_reducer";
import RestorePayslipReducer from "../restore_payslip_reducer";
import ResubmitPayslipReducer from "../resubmit_payslip_reducer";
import SignPayslipReducer from "../sign_payslip_reducer";
import SubmitPayslipReducer from "../submit_payslip_reducer";
import UpdateCompanyReducer from "../update_company_reducer";
import UpdateDeductionsTemplateReducer from "../update_deductions_template_reducer";
import UpdateDraftReducer from "../update_draft_reducer";
import UpdateEarningsTemplateReducer from "../update_earnings_template_reducer";
import UpdateEmployeeReducer from "../update_employee_reducer";
import UpdateFieldVisibilityReducer from "../update_field_visibility_reducer";
import UpdateMyProfileReducer from "../update_my_profile_reducer";

export type AddDeductionsTemplateParams = __Infer<typeof AddDeductionsTemplateReducer>;
export type AddEarningsTemplateParams = __Infer<typeof AddEarningsTemplateReducer>;
export type ChangePasswordParams = __Infer<typeof ChangePasswordReducer>;
export type CreateEmployeeAccountParams = __Infer<typeof CreateEmployeeAccountReducer>;
export type DeleteDeductionsTemplateParams = __Infer<typeof DeleteDeductionsTemplateReducer>;
export type DeleteDraftParams = __Infer<typeof DeleteDraftReducer>;
export type DeleteEarningsTemplateParams = __Infer<typeof DeleteEarningsTemplateReducer>;
export type DeleteEmployeeParams = __Infer<typeof DeleteEmployeeReducer>;
export type HidePayslipParams = __Infer<typeof HidePayslipReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type RejectPayslipParams = __Infer<typeof RejectPayslipReducer>;
export type RestorePayslipParams = __Infer<typeof RestorePayslipReducer>;
export type ResubmitPayslipParams = __Infer<typeof ResubmitPayslipReducer>;
export type SignPayslipParams = __Infer<typeof SignPayslipReducer>;
export type SubmitPayslipParams = __Infer<typeof SubmitPayslipReducer>;
export type UpdateCompanyParams = __Infer<typeof UpdateCompanyReducer>;
export type UpdateDeductionsTemplateParams = __Infer<typeof UpdateDeductionsTemplateReducer>;
export type UpdateDraftParams = __Infer<typeof UpdateDraftReducer>;
export type UpdateEarningsTemplateParams = __Infer<typeof UpdateEarningsTemplateReducer>;
export type UpdateEmployeeParams = __Infer<typeof UpdateEmployeeReducer>;
export type UpdateFieldVisibilityParams = __Infer<typeof UpdateFieldVisibilityReducer>;
export type UpdateMyProfileParams = __Infer<typeof UpdateMyProfileReducer>;

